version: "3.7"

services:

  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - redis:/var/lib/redis/data

  photonia:
    container_name: photonia
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      HISTFILE: /root/history/.bash_history
    stdin_open: true
    tty: true
    volumes:
      - .:/photonia
      - bundle:/root/.bundle
      - bash_history:/root/history/

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/photonia
      - bundle:/root/.bundle

volumes:
  postgres:
  bash_history:
  bundle:
  redis:
