version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6-node
    steps:
      - checkout
      - ruby/install-deps:
          with-cache: true
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    docker:
      - image: cimg/ruby:2.6-node
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: photonia
          POSTGRES_DB: photonia_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "5"
      BUNDLE_RETRY: "3"
      PHOTONIA_DATABASE_URL: "postgres://photonia:password@127.0.0.1/"
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Install PostgreSQL client
          command: |
          curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-11
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: rspec
          command: bundle exec rspec
      # Run rspec in parallel
      # - ruby/rspec-test
      # - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
